export const welcomeLogoSize = '120px';

export const clearSearchOnHome = true;

export const maxSectionImages = 3;

export const linkDensity = 'high';

export const articleTone = "encyclopedic, detailed, and internally consistent";

export const sarcasticArticleTone = "bitingly sarcastic and dismissive, while still being internally consistent";

export const realisticArticleTone = "grounded, plausible, and scientific-sounding, avoiding overt magic or high fantasy elements. The tone should be similar to a real-world encyclopedia, but for a fictional topic that could conceivably exist.";

export const defaultNumberOfSections = 4;

export const cohesionCheckPrompt = `You are a contextual consistency checker for a fictional encyclopedia. You will be given a "parent" article's title and summary, and a "child" article's title and summary. The child article was generated by clicking a link within the parent article.

Your tasks are:
1. Determine if the child article is a logical, coherent, and contextually relevant continuation of the concept it was linked from in the parent article.
2. If it is NOT relevant, suggest a single, better topic title that WOULD be relevant to the parent article's context.

Respond with a single JSON object with no other text, following this schema:
{
  "isRelevant": boolean,
  "suggestedTopic": "string" | null (only provide a string if isRelevant is false)
}`;

export const numRandomTopics = 5;

export const scrollToTopOnSelfLink = true;

export const selfLinkScrollBehavior = 'smooth';

export const enableSettingsPanel = true;
export const settingsPanelPosition = 'right';

export const amboxChance = 0.2;

export const linkCohesionChance = 0.95;

export const chaosChance = 0.01;

export const redLinkChance = 0.15;

// --- Static Configuration ---
export const nationInfoboxKeys = ['Capital', 'Government', 'Ideology', 'Population', 'Global Standing'];
export const nationSectionHeadings = ['History', 'Government and Politics', 'List of Leaders', 'Major Conflicts'];
export const taxonRanks = ["Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"];
